name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install & Lint TS
      run: |
        cd ts-backend
        npm install
        npx tsc --noEmit
        npx eslint src/

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build Go
      run: |
        cd go-backend
        go build
